### PR TITLE
Fixed various issues

### PR DESCRIPTION
**Pull request by otadmor**

### CODE REVIEW

**Comment by otadmor** [comment]
How do I edit the commit message without creating a new history line in github?

**Comment by oleavr** [comment]
Use interactive rebasing (`git rebase -i`) and force-push. PR will get updated automatically. (Make a backup first though.)

**Comment by otadmor** [comment]
Are these ok?

**Comment by oleavr** [comment]
The `[Tag] ` prefixes should be dropped (for consistency), and full stop removed from the first line, and `accedentely mode change` should be `accidental mode change`.

**Comment by oleavr** [comment]
Thanks!

**Pull request merged**
